# -*- coding: utf-8 -*-
"""python_basics_<Avaneesh>

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QhW8Np8J-mPlCBWxThlG7OoBYnfe5OD
"""

# Task 1: Variables and Data Types
name = "Avaneesh"
age = 20
height = 1.75
is_student = True

# Print all values in a single print statement
print(name, age, height, is_student)

# Task 2: String Formatting
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

# Task 3: Arithmetic Operations

# Age calculations
age_in_months = age * 12
age_in_days = age * 365
remainder = age % 7
age_squared = age ** 2

# Printing results
print("Age in months:", age_in_months)
print("Age in days:", age_in_days)
print("Remainder when age is divided by 7:", remainder)
print("Age squared:", age_squared)